module.exports = class CanvasStyling

	# Color
	@CHART_LINES_FILL: "#C4C2C2"
	@CONNECTING_PREDICTION_LINES: "#3079F0"
	@AXIS_LABEL_OPACITY: 1
	@SELECTED_SHAPE_BLUE: "#3AB8FC"
	@BLACK: "#000"
	@WHITE: "#FFF"

	# Shapes
	@MIN_RADIUS: 2
	@MAX_RADIUS: 30

	# Positioning
	@SCATTER_CHART_AXIS_PADDING: CanvasStyling.MAX_RADIUS
	@CHART_PAD = 80

	# Animation
	@DEFAULT_ANIMATION_DURATION: 500
	@QUICK_ANIMATION_DURATION: 300